version: '3.8'

services:
  backend:
    image: recovery-backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: recovery-frontend
    ports:
      - "80:80"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "P@ssw0rd1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"